version: '2'

services:
  cassandra:
    build: ./cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
  cassandra-jdbc-client:
    build: ./cassandra-jdbc-client
    stdin_open: true
    tty: true
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_HOST=cassandra
  cassandra-odbc-client:
    build: ./cassandra-odbc-client
    stdin_open: true
    tty: true
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_HOST=cassandra
      - ODBCINI=/opt/simba/cassandraodbc/Setup/odbc.ini
      - ODBCSYSINI=/opt/simba/cassandraodbc/Setup/
      - SIMBACASSANDRAODBC=/opt/simba/cassandraodbc/lib/64/simba.cassandraodbc.ini
volumes:
  cassandra_data:
    driver: local
